server:
  port: 8002 #指定运行端口
spring:
  application:
    name: eureka-server2 #指定服务名称
eureka:
  instance:
    hostname: eurekaserver2.com #指定主机地址  127.0.0.1 必须用域名否则无法生效
  client:
    serviceUrl:
      defaultZone: http://eurekaserver3.com:8003/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true



