server:
  port: 8003 #指定运行端口
spring:
  application:
    name: eureka-server3 #指定服务名称
eureka:
  instance:
    hostname: eurekaserver3.com #指定主机地址  127.0.0.1  必须用域名否则无法生效
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2.com:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true



